version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  transferme_mongodb:
    container_name: ${MONGO_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} # Lưu ý 2 biến này từ file env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} # và dùng --env-file để đọc từ .env.dev
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo-data:/data/db # Mount data ra bên ngoài để tránh dữ liệu bị xóa khi remove container 
    restart: unless-stopped

  cache:
    image: redis:6
    env_file:
      - .env
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: