export enum SERVICES {
	AUTH_SERVICE = 'AUTH_SERVICE',
	USER_SERVICE = 'USER_SERVICE',
	FRIENDSHIP_SERVICE = 'FRIENDSHIP_SERVICE',
	GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
	GOOGLE_AUTH_CLIENT = 'GOOGLE_AUTH_CLIENT',
	REFRESH_TOKEN_STORAGE = 'REFRESH_TOKEN_STORAGE',
}
