export enum SERVICES {
	AUTH_SERVICE = 'AUTH_SERVICE',
	USER_SERVICE = 'USER_SERVICE',
	FRIEND_SERVICE = 'FRIEND_SERVICE',
	FRIEND_REQUEST_SERVICE = 'FRIEND_REQUEST_SERVICE',
	GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
	GOOGLE_AUTH_CLIENT = 'GOOGLE_AUTH_CLIENT',
	REFRESH_TOKEN_STORAGE = 'REFRESH_TOKEN_STORAGE',
}

export enum ROUTES {
	AUTH = 'auth',
	USER = 'user',
	FRIEND = 'friend',
	TRANSFER = 'transfer',
	FRIEND_REQUEST = 'friend-request',
}

export enum SERVER_EVENTS {
	FRIEND_REQUEST_CREATE = 'friendrequest.create',
	FRIEND_REQUEST_ACCEPTED = 'friendrequest.accepted',
	FRIEND_REQUEST_REJECTED = 'friendrequest.rejected',
	FRIEND_REQUEST_CANCELLED = 'friendrequest.cancelled',
	FRIEND_REQUEST_CANCEL = 'friendrequest.cancel',
	FRIEND_REMOVED = 'friend.removed',
}

export enum SOCKET_EVENTS {
	// Transfer
	SEND_FILE = 'SEND_FILE',
	WAIT_TRANSFER_ACCEPTED = 'WAIT_TRANSFER_ACCEPTED',
	SUCCESS_TRANSFER = 'SUCCESS_TRANSFER',
	ERROR_TRANSFER = 'ERROR_TRANSFER',
	CANCEL_TRANSFER = 'CANCEL_TRANSFER',
	ON_CANCEL_TRANSFER = 'ON_CANCEL_TRANSFER',
	NEW_CONNECTION = 'NEW_CONNECTION',
	USER_LOGOUT = 'USER_LOGOUT',
	REQUEST_SEND_FILE = 'REQUEST_SEND_FILE',
	REPLY_TO_REQUEST = 'REPLY_TO_REQUEST',
	REFUSE_REQUEST = 'REFUSE_REQUEST',
	ACCEPT_REQUEST = 'ACCEPT_REQUEST',
	RECEIVE_FILE = 'RECEIVE_FILE',
	TRANSFERING = 'TRANSFERING',
	AVAILABLE = 'AVAILABLE',
	ACK_RECEIVE_FILE = 'ACK_RECEIVE_FILE',
	ON_ACK_RECEIVE_FILE = 'ON_ACK_RECEIVE_FILE',

	// Friend
	FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
	FRIEND_REQUEST_REJECTED = 'FRIEND_REQUEST_REJECTED',
}
